-- This file is additional localization file for YuLun's Mod Menu Revamped
-- This file is not used by vanilla mod menu
-- https://github.com/YuLun-bili/Mod-Menu-Revamped
-- https://crowdin.com/project/yulun-td-mmre


-- language index:
-- 0	en
-- 1	fr
-- 2	es
-- 3	it
-- 4	de
-- 5	zh
-- 6	jp
-- 7	ru
-- 8	pl

locLangLookup = {
	INDEX = 			{0, 1, 2, 3, 4, 5, 6, 7, 8},
	new = 				{
		"New",
		"Nouveau",
		"Nuevo",
		"Nuovo",
		"Neu",
		"新的",
		"新着",
		"Новые",
		"Nowy",
	},
	rename = 			{
		"Rename",
		"Renommer",
		"Renombrar",
		"Rinominare",
		"Umbenennen",
		"重命名",
		"名前を変更する",
		"Переименовать",
		"Zmień nazwę",
	},
	duplicate = 		{
		"Duplicate",
		"Dupliquer",
		"Duplicar",
		"Duplicato",
		"Duplizieren",
		"副本",
		"複製",
		"Дублировать",
		"Duplikuj",
	},
	delete = 			{
		"Delete",
		"Supprimer",
		"Borrar",
		"Eliminare",
		"Löschen",
		"删除",
		"Delete",
		"Удалить",
		"Usuń",
	},
	enableAll = 		{
		"Enable all",
		"Tout activer",
		"Habilitar todos",
		"Attiva tutti",
		"Alles aktivieren",
		"全部启用",
		"Enable all",
		"Включить Всё",
		"Włącz wszystko",
	},
	disableAll = 		{
		"Disable all",
		"Tout désactiver",
		"Deshabilitar todos",
		"Disabilita tutti",
		"Alles aufheben",
		"全部禁用",
		"Disable all",
		"Выключить Всё",
		"Wyłącz wszystko",
	},
	modsRefreshed = 	{
		"Mods Refreshed",
		"Mods Actualisés",
		"Refrescar Mods",
		"Mods Aggiornati",
		"Mods Aktualisiert",
		"模组已刷新",
		"Mods Refreshed",
		"Моды обновлены",
		"Odświeżenie Modów",
	},
	renameCol = 	{
		"[rename]",
		"[renommer]",
		"[renombrar]",
		"[rinominare]",
		"[umbenennen]",
		"[重命名]",
		"[rename]",
		"[переименовать]",
		"[zmień nazwę]",
	},
	searchMod = 	{
		"[search mod]",
		"[recherche un mod]",
		"[buscar mod]",
		"[cerca mod]",
		"[suche mod]",
		"[搜索模组]",
		"[search mod]",
		"[искать мод]",
		"[tryb wyszukania]",
	},
	newCol = 	{
		"[new collection]",
		"[nouvelle collection]",
		"[nueva colección]",
		"[nuova collezione]",
		"[neue sammlung]",
		"[新建合集]",
		"[new collection]",
		"[новая коллекция]",
		"[nowa kolekcja]",
	},
	collection = 		{
		"Collection",
		"Collection",
		"Colección",
		"Collezione",
		"Sammlung",
		"合集",
		"Collection",
		"Коллекция",
		"Kolekcja",
	},
	delColConfirm = 	{
		"Are you sure you want to delete this collection?",
		"Êtes-vous sûr de vouloir supprimer cette collection ?",
		"¿Estás seguro de querer borrar está colección?",
		"Sei sicuro di voler eliminare questa collezione?",
		"Möchten Sie diese Sammlung wirklich löschen?",
		"你确定你要删除此合集吗？",
		"Are you sure you want to delete this collection?",
		"Вы уверены, что хотите удалить эту коллекцию?",
		"Czy na pewno chcesz usunąć tę kolekcję?",
	},
	disableModsColAsk = {
		"Do you want to disable all unlisted mods at the same time?",
		"Souhaitez-vous désactiver tout les mods non listés en même temps ?",
		"¿Quieres desactivar todos los mods no listados al mismo tiempo?",
		"Vuoi disattivare tutte le mod non elencate allo stesso tempo?",
		"Möchtest du alle nicht aufgelisteten Mods gleichzeitig deaktivieren?",
		"你想要同时禁用全部未列出的模组吗？",
		"Do you want to disable all unlisted mods at the same time?",
		"Хотите ли вы также отключить все неперечисленные моды?",
		"Czy chcesz wyłączyć jednocześnie wszystkie nieumieszczone na liście modyfikacje?",
	},
	applyCol = 			{
		"Apply collection",
		"Appliquer la collection",
		"Activar colección",
		"Applica collezione",
		"Sammlung anwenden",
		"启用合集",
		"Apply collection",
		"Применить коллекцию",
		"Zastosuj kolekcję",
	},
	disuseCol = 		{
		"Disuse collection",
		"Ne plus utiliser la collection",
		"Desactivar colección",
		"Disattiva raccolta",
		"Sammlung deaktivieren",
		"停用合集",
		"Disuse collection",
		"Сбросить коллекцию",
		"Nie używaj kolekcji",
	},
	errorColShort = 	{
		"Name too short, min 3 charactors",
		"Nom trop court, 3 caractères minimum",
		"Nombre demasiado corto, mínimo 3 caracteres",
		"Nome troppo breve, minimo 3 caratteri",
		"Name zu kurz, min. 3 Zeichen",
		"名称过短，至少3个字符",
		"Name too short, min 3 charactors",
		"Имя слишком короткое, минимум 3 символа",
		"Nazwa zbyt krótka, użyj minimum 3 znaków",
	},
	errorColLong = 		{
		"Name too long, max 20 charactors",
		"Nom trop long, 20 caractères maximum",
		"Nombre demasiado largo, máximo 20 caracteres",
		"Nome troppo lungo, massimo 20 caratteri",
		"Name zu lang, max. 20 Zeichen",
		"名称过长，至多20个字符",
		"Name too long, max 20 charactors",
		"Имя слишком длинное, максимум 20 символов",
		"Nazwa zbyt długa, użyj maksymalnie 20 znaków",
	},
	settings = 			{
		"Settings",
		"Paramètre",
		"Configuración",
		"Impostazioni",
		"Einstellungen",
		"设置",
		"Settings",
		"Настройки",
		"Ustawienia",
	},
	setting1 = 			{
		"Built-in mod path",
		"Chemin du mod intégré",
		"Ruta de mod integrados",
		"Percorso delle mod integrato",
		"Integrierter Mod-Pfad",
		"内置模组路径",
		"Built-in path",
		"Путь к встроенному моду",
		"Wbudowana ścieżka modyfikacji",
	},
	setting2 = 			{
		"Workshop mod path",
		"Chemin du mod du Workshop",
		"Ruta de mods del Workshop",
		"Percorso mod Workshop",
		"Workshop-Mod-Pfad",
		"工坊模组路径",
		"Workshop path",
		"Путь к мастерской модов",
		"Ścieżka do modyfikacji z warsztatu",
	},
	setting3 = 			{
		"Initial category",
		"Catégorie initiale",
		"Categoría inicial",
		"Categoria iniziale",
		"Anfangskategorie",
		"初始类别",
		"Initial category",
		"Начальная категория",
		"Kategoria początkowa",
	},
	setting4 = 			{
		"Remember last selected mod",
		"Mémoriser le dernier mod sélectionné",
		"Recordar último mod seleccionado",
		"Ricorda l'ultima mod selezionata",
		"Letzten Mod erinnern",
		"记住最后选择模组",
		"Remember last",
		"Запомнить последний выбранный мод",
		"Zapamiętaj ostatnio wybraną modyfikację",
	},
	setting4ex = 		{
		"overwrite previous",
		"écraser le précédent",
		"sobrescribir previos",
		"sovrascrivi precedente",
		"vorherige überschreiben",
		"覆盖上一项",
		"overwrite previous",
		"перезаписать предыдущий",
		"nadpisz poprzednie",
	},
	setting5 = 		{
		"Reset filter when changing mod category",
		"Reset filter when changing mod category",
		"Reset filter when changing mod category",
		"Reset filter when changing mod category",
		"Reset filter when changing mod category",
		"更改模组类别时重置过滤选项",
		"Reset filter when changing mod category",
		"Reset filter when changing mod category",
		"Reset filter when changing mod category",
	},
	cateLocalShort =	{
		"Local",
		"Locale",
		"Local",
		"Locali",
		"Lokal",
		"本地",
		"Local",
		"Локальный",
		"Lokalny",
	},
	cateWorkshopShort =	{
		"Workshop",
		"Workshop",
		"Workshop",
		"Workshop",
		"Workshop",
		"工坊",
		"Workshop",
		"Мастерская",
		"Warsztat",
	},
	cateBuiltInShort =	{
		"Built-in",
		"Intégré",
		"Integrados",
		"Integrato",
		"Integriert",
		"内置",
		"Built-in",
		"Встроенное",
		"Wbudowany",
	},
	filterModeAlphabet ={
		"Alphabetical",
		"Alphabétique",
		"Alfabético",
		"Alphabetical",
		"Alphabetisch",
		"字母",
		"Alphabetical",
		"По алфавиту",
		"Alfabetycznie",
	},
	filterModeUpdate =	{
		"Updated",
		"Mis à jour",
		"Actualizados",
		"Updated",
		"Aktualisiert",
		"更新",
		"Updated",
		"Обновленно",
		"Zaktualizowano",
	},
	filterModeSubscribe ={
		"Subscribed",
		"Abonné",
		"Suscritos",
		"Subscribed",
		"Abonniert",
		"订阅",
		"Subscribed",
		"Подписанные",
		"Subskrybowane",
	},
	modSavegameSpace =	{
		"Savegame Space: ",
		"Espace de sauvegarde : ",
		"Espacio en Savegame: ",
		"Savegame Space: ",
		"Savegame Space: ",
		"存档空间：",
		"Savegame Space: ",
		"Размер Сохранённой Игры: ",
		"Spacja savegame: ",
	},
	clearModData =		{
		"This mod occupied %d B in savegame file. Do you want to clear it?",
		"Ce mod a occupé %d B du fichier de sauvegarde. Voulez-vous le supprimer ?",
		"Este mod ha ocupado %d B en el archivo de guardado. ¿Quieres liberarlo?",
		"This mod occupied %d B in savegame file. Do you want to clear it?",
		"This mod occupied %d B in savegame file. Do you want to clear it?",
		"此模组占用了存档文件中 %d B 的空间。你想要清空它吗？",
		"This mod occupied %d B in savegame file. Do you want to clear it?",
		"Этот мод оккупировал %d Байтов в сохранённой игре. Хотите ли вы его очистить?",
		"Ten mod zajmował %d B w pliku zapisu gry. Czy chcesz to wyczyścić?",
	},
	clearUnknownData =		{
		"Unknown mods (e.g.: deleted) occupied %d B in savegame file in total. Do you want to clear them?",
		"Des mods inconnus (par exemple : supprimés) ont occupé %d B dans le fichier de sauvegarde au total. Voulez-vous les effacer ?",
		"Mods desconocidos (por ejemplo: borrados) ocupados %d B en el archivo de guardado en total. ¿Quieres eliminarlos?",
		"Unknown mods (e.g.: deleted) occupied %d B in savegame file in total. Do you want to clear them?",
		"Unknown mods (e.g.: deleted) occupied %d B in savegame file in total. Do you want to clear them?",
		"未知模组（如：已删除）总计占用了存档文件中 %d B 的空间。你想要清空它们吗？",
		"Unknown mods (e.g.: deleted) occupied %d B in savegame file in total. Do you want to clear them?",
		"Неизвестные моды (например, удалённые) оккупируют %d Байтов в вашей сохранённой игре. Хотите ли вы отчистить их?",
		"Nieznane mody (np. usunięte) zajmowały w sumie %d B w pliku zapisu gry. Czy chcesz je wyczyścić?",
	},
	tooltipClearUnknownData ={
		"Clean-up unknown savegame data",
		"Clean-up unknown savegame data",
		"Limpiar datos de guardado desconocidos",
		"Clean-up unknown savegame data",
		"Clean-up unknown savegame data",
		"清扫未知存档数据",
		"Clean-up unknown savegame data",
		"Отчистить неизвестную дату сохранённой игры",
		"Wyczyść nieznane dane zapisanej gry",
	},
	tooltipChooseRandomMod ={
		"Select a random mod from \"%s\" list",
		"Select a random mod from \"%s\" list",
		"Selecciona un mod aleatorio de la lista \"%s\"",
		"Select a random mod from \"%s\" list",
		"Wähle eine zufällige Mod aus der Liste \"%s\"",
		"从“%s”列表中随机选择模组",
		"Select a random mod from \"%s\" list",
		"Выбрать рандомный мод из \"%s\" листа",
		"Wybierz losowy mod z \"%s\"",
	},
	tooltipRefresh =	{
		"Refresh",
		"Refresh",
		"Recargar",
		"Refresh",
		"Neuladen",
		"刷新",
		"Refresh",
		"Обновить",
		"Odśwież",
	},
	collectEnabledToColAsk ={
		"Do you want to remove all disabled/other mods from collection at the same time?",
		"Do you want to remove all disabled/other mods from collection at the same time?",
		"¿Quieres eliminar todos los mods deshabilitados/de la colección al mismo tiempo?",
		"Do you want to remove all disabled/other mods from collection at the same time?",
		"Do you want to remove all disabled/other mods from collection at the same time?",
		"你想要同时将已禁用/其它模组从合集中移除吗？",
		"Do you want to remove all disabled/other mods from collection at the same time?",
		"Хотите ли вы также убрать все выключенные/другие моды из коллекции?",
		"Czy chcesz usunąć wszystkie wyłączone/inne mody z tej kolekcji naraz?",
	},
	collectEnabled =	{
		"Collect all enabled",
		"Collect all enabled",
		"Agregar habilitados a colección",
		"Collect all enabled",
		"Alle aktivierten einsammeln",
		"收藏全部启用模组",
		"Collect all enabled",
		"Собрать все включённые",
		"Zbierz wszystkie włączone",
	}
}