-- This file is additional localization file for YuLun's Mod Menu Revamped
-- This file is not used by vanilla mod menu
-- https://github.com/YuLun-bili/Mod-Menu-Revamped
-- https://crowdin.com/project/yulun-td-mmre


-- language index:
-- 1	en
-- 2	fr
-- 3	es
-- 4	it
-- 5	de
-- 6	zh
-- 7	jp
-- 8	ru
-- 9	pl

locLangLookup = {
	new = 				{
		"New",
		"Nouveau",
		"Nuevo",
		"Nuovo",
		"Neu",
		"新的",
		"New",
		"Новые",
		"Nowy",
	},
	rename = 			{
		"Rename",
		"Renommer",
		"Renombrar",
		"Rinominare",
		"Umbenennen",
		"重命名",
		"Rename",
		"Переименовать",
		"Zmień nazwę",
	},
	duplicate = 		{
		"Duplicate",
		"Dupliquer",
		"Duplicar",
		"Duplicato",
		"Duplizieren",
		"副本",
		"Duplicate",
		"Дублировать",
		"Duplikuj",
	},
	delete = 			{
		"Delete",
		"Supprimer",
		"Borrar",
		"Eliminare",
		"Löschen",
		"删除",
		"Delete",
		"Удалить",
		"Usuń",
	},
	enableAll = 		{
		"Enable all",
		"Tout activer",
		"Habilitar todos",
		"Attiva tutti",
		"Alles aktivieren",
		"全部启用",
		"Enable all",
		"Включить Всё",
		"Włącz wszystko",
	},
	disableAll = 		{
		"Disable all",
		"Tout désactiver",
		"Deshabilitar todos",
		"Disabilita tutti",
		"Alles aufheben",
		"全部禁用",
		"Disable all",
		"Выключить Всё",
		"Wyłącz wszystko",
	},
	modsRefreshed = 	{
		"Mods Refreshed",
		"Mods Actualisés",
		"Refrescar Mods",
		"Mods Aggiornati",
		"Mods Aktualisiert",
		"模组已刷新",
		"Mods Refreshed",
		"Моды обновлены",
		"Odświeżenie Modów",
	},
	renameCol = 	{
		"[rename]",
		"[renommer]",
		"[renombrar]",
		"[rinominare]",
		"[umbenennen]",
		"[重命名]",
		"[rename]",
		"[переименовать]",
		"[zmień nazwę]",
	},
	searchMod = 	{
		"[search mod]",
		"[search mod]",
		"[buscar mod]",
		"[cerca mod]",
		"[suche mod]",
		"[搜索模组]",
		"[search mod]",
		"[искать мод]",
		"[tryb wyszukania]",
	},
	newCol = 	{
		"[new collection]",
		"[nouvelle collection]",
		"[nueva colección]",
		"[nuova collezione]",
		"[neue sammlung]",
		"[新建合集]",
		"[new collection]",
		"[новая коллекция]",
		"[nowa kolekcja]",
	},
	collection = 		{
		"Collection",
		"Collection",
		"Colección",
		"Collezione",
		"Sammlung",
		"合集",
		"Collection",
		"Коллекция",
		"Kolekcja",
	},
	delColConfirm = 	{
		"Are you sure you want to delete this collection?",
		"Êtes-vous sûr de vouloir supprimer cette collection?",
		"¿Estás seguro de querer borrar está colección?",
		"Sei sicuro di voler eliminare questa collezione?",
		"Möchten Sie diese Sammlung wirklich löschen?",
		"你确定你要删除此合集吗？",
		"Are you sure you want to delete this collection?",
		"Вы уверены, что хотите удалить эту коллекцию?",
		"Czy na pewno chcesz usunąć tę kolekcję?",
	},
	disableModsColAsk = {
		"Do you want to disable all unlisted mods at the same time?",
		"Souhaitez-vous désactiver tout les mods non listés en même temps?",
		"¿Quieres desactivar todos los mods no listados al mismo tiempo?",
		"Vuoi disattivare tutte le mod non elencate allo stesso tempo?",
		"Möchtest du alle nicht aufgelisteten Mods gleichzeitig deaktivieren?",
		"你想要同时禁用全部未列出的模组吗？",
		"Do you want to disable all unlisted mods at the same time?",
		"Хотите ли вы также отключить все неперечисленные моды?",
		"Czy chcesz wyłączyć jednocześnie wszystkie nieumieszczone na liście modyfikacje?",
	},
	applyCol = 			{
		"Apply collection",
		"Apply collection",
		"Activar colección",
		"Applica collezione",
		"Sammlung anwenden",
		"启用合集",
		"Apply collection",
		"Применить коллекцию",
		"Zastosuj kolekcję",
	},
	disuseCol = 		{
		"Disuse collection",
		"Disuse collection",
		"Desactivar colección",
		"Disattiva raccolta",
		"Sammlung deaktivieren",
		"停用合集",
		"Disuse collection",
		"Сбросить коллекцию",
		"Nie używaj kolekcji",
	},
	errorColShort = 	{
		"Name too short, min 3 charactors",
		"Name too short, min 3 charactors",
		"Nombre demasiado corto, mínimo 3 caracteres",
		"Nome troppo breve, minimo 3 caratteri",
		"Name zu kurz, min. 3 Zeichen",
		"名称过短，至少3个字符",
		"Name too short, min 3 charactors",
		"Имя слишком короткое, минимум 3 символа",
		"Nazwa zbyt krótka, użyj minimum 3 znaków",
	},
	errorColLong = 		{
		"Name too long, max 20 charactors",
		"Name too long, max 20 charactors",
		"Nombre demasiado largo, máximo 20 caracteres",
		"Nome troppo lungo, massimo 20 caratteri",
		"Name zu lang, max. 20 Zeichen",
		"名称过长，至多20个字符",
		"Name too long, max 20 charactors",
		"Имя слишком длинное, максимум 20 символов",
		"Nazwa zbyt długa, użyj maksymalnie 20 znaków",
	},
	settings = 			{
		"Settings",
		"Paramètre",
		"Configuración",
		"Impostazioni",
		"Einstellungen",
		"设置",
		"Settings",
		"Настройки",
		"Ustawienia",
	},
	setting1 = 			{
		"Built-in mod path",
		"Built-in path",
		"Ruta de mod integrados",
		"Percorso delle mod integrato",
		"Integrierter Mod-Pfad",
		"内置模组路径",
		"Built-in path",
		"Путь к встроенному моду",
		"Wbudowana ścieżka modyfikacji",
	},
	setting2 = 			{
		"Workshop mod path",
		"Workshop path",
		"Ruta de mods del Workshop",
		"Percorso mod workshop",
		"Workshop-Mod-Pfad",
		"工坊模组路径",
		"Workshop path",
		"Путь к мастерской модов",
		"Ścieżka do modyfikacji z warsztatu",
	},
	setting3 = 			{
		"Initial category",
		"Initial category",
		"Categoría inicial",
		"Categoria iniziale",
		"Anfangskategorie",
		"初始类别",
		"Initial category",
		"Начальная категория",
		"Kategoria początkowa",
	},
	setting4 = 			{
		"Remember last selected mod",
		"Remember last",
		"Recordar último mod seleccionado",
		"Ricorda l'ultima mod selezionata",
		"Letzten Mod erinnern",
		"记住最后选择模组",
		"Remember last",
		"Запомнить последний выбранный мод",
		"Zapamiętaj ostatnio wybraną modyfikację",
	},
	setting4ex = 		{
		"overwrite previous",
		"écraser le précédent",
		"sobrescribir previos",
		"sovrascrivi precedente",
		"vorherige überschreiben",
		"覆盖上一项",
		"overwrite previous",
		"перезаписать предыдущий",
		"nadpisz poprzednie",
	},
	cateLocalShort =	{
		"Local",
		"Local",
		"Local",
		"Locali",
		"Lokal",
		"本地",
		"Local",
		"Локальный",
		"Lokalny",
	},
	cateWorkshopShort =	{
		"Workshop",
		"Workshop",
		"Workshop",
		"Workshop",
		"Workshop",
		"工坊",
		"Workshop",
		"Мастерская",
		"Warsztat",
	},
	cateBuiltInShort =	{
		"Built-in",
		"Built-in",
		"Integrados",
		"Integrato",
		"Integriert",
		"内置",
		"Built-in",
		"Встроенное",
		"Wbudowany",
	},
	filterModeAlphabet ={
		"Alphabetical",
		"Alphabetical",
		"Alphabetical",
		"Alphabetical",
		"Alphabetical",
		"字母",
		"Alphabetical",
		"Alphabetical",
		"Alphabetical",
	},
	filterModeUpdate =	{
		"Updated",
		"Updated",
		"Updated",
		"Updated",
		"Updated",
		"更新",
		"Updated",
		"Updated",
		"Updated",
	},
	filterModeSubscribe ={
		"Subscribed",
		"Subscribed",
		"Subscribed",
		"Subscribed",
		"Subscribed",
		"订阅",
		"Subscribed",
		"Subscribed",
		"Subscribed",
	}
}